#!/bin/bash

for i in 0xffff0000 0xffff8000 0xffffc000 0xffffe000 0xfffff000 0xfffff800 0xfffffc00 0xfffffe00 0xffffff00 0xffffff80
do
  for k in {0..99}
  do
    psabpf-ctl table add pipe 99 ingress_tbl_fwd id 1 key 48.$k.0.0^$i data $PORT1_INDEX
  done
done
